import type {Metadata} from "next";
import {PolicyPage} from "@/components/policy-page";

export const metadata:Metadata={title:"Trocas e Devoluções",description:"Entenda como solicitar troca, devolução ou reembolso na S&A Parfum."};
export default function Page(){return <PolicyPage title="Política de Trocas e Devoluções" intro="Nosso processo respeita o Código de Defesa do Consumidor e foi pensado para tornar solicitações de troca, arrependimento e devolução mais claras.">
  <h2>1. Direito de arrependimento</h2><p>Em compras realizadas pela internet, você pode solicitar a devolução em até 7 dias corridos contados do recebimento, conforme o artigo 49 do Código de Defesa do Consumidor. Para iniciar o processo, envie o número do pedido e o motivo do contato para nosso canal de atendimento.</p>
  <h2>2. Condições para devolução</h2><p>Enquanto decide sobre o arrependimento, conserve o produto, a embalagem original, acessórios, brindes e documento fiscal. O perfume deve ser devolvido com cuidado e sem consumo além do necessário para verificar sua natureza e características. Essas condições não limitam direitos assegurados por lei em caso de defeito ou divergência.</p>
  <h2>3. Produto avariado, com defeito ou diferente</h2><p>Se receber um item avariado, com vazamento, defeito aparente, incompleto ou diferente do pedido, fotografe o produto e a embalagem e entre em contato assim que identificar o problema. A solicitação será analisada de acordo com os prazos e garantias previstos na legislação aplicável.</p>
  <h2>4. Quando recusar a entrega</h2><p>Recomendamos recusar o pacote se a embalagem estiver aberta, violada ou severamente danificada, se houver vazamento aparente ou se os produtos estiverem em desacordo com o pedido. Avise-nos imediatamente para que possamos acompanhar a ocorrência.</p>
  <h2>5. Como enviar o produto</h2><p>Após a solicitação, enviaremos as orientações de postagem ou coleta. Quando a devolução decorrer de arrependimento dentro do prazo legal, defeito, avaria ou erro da S&amp;A Parfum, o procedimento será disponibilizado sem custo ao consumidor. Não envie produtos antes de receber as instruções.</p>
  <h2>6. Análise</h2><p>Ao receber o item, verificaremos as condições e a correspondência com a solicitação. A análise não será usada para afastar direitos legais. Quando houver sinais de dano causado após o recebimento, uso incompatível, armazenamento inadequado ou ausência de componentes não relacionados ao problema relatado, entraremos em contato com o resultado e os próximos passos.</p>
  <h2>7. Troca e disponibilidade</h2><p>Uma troca poderá ser realizada pelo mesmo produto, conforme disponibilidade de estoque. Se ele estiver indisponível, você poderá escolher outro item, receber crédito quando aceitar essa alternativa ou solicitar o reembolso devido.</p>
  <h2>8. Reembolso</h2><p>Depois da aprovação da devolução, o reembolso será solicitado pelo mesmo meio de pagamento utilizado na compra sempre que possível. No Pix, o valor será devolvido para uma conta vinculada ao titular da compra. No cartão, o prazo de exibição do estorno depende do emissor e do fechamento da fatura. Fretes devidos conforme a legislação também serão restituídos.</p>
  <h2>9. Produtos adquiridos fora do site</h2><p>Para vendas registradas presencialmente ou por atendimento direto, as regras variam conforme o motivo da solicitação e a legislação aplicável. O direito de arrependimento de 7 dias descrito acima se aplica às contratações realizadas fora do estabelecimento comercial, inclusive pela internet.</p>
</PolicyPage>}
