import { ArrowRight, Check, Gem, PackageCheck, ShieldCheck, Sparkles, Star } from "lucide-react";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { ProductCard } from "@/components/product-card";
import { products } from "@/lib/catalog";

export default function Home() { return <><Header/><main>
  <section className="hero"><div className="hero-art" aria-hidden="true"><span>S</span><i>&amp;</i><span>A</span></div><div className="container-site hero-content"><p className="eyebrow">Perfumaria de alta expressão</p><h1>Perfumes que<br/><em>marcam presença.</em></h1><p className="hero-copy">Fragrâncias originais, importadas e árabes selecionadas para transformar momentos em memórias.</p><div className="hero-actions"><a className="btn-primary" href="/perfumes">Comprar agora <ArrowRight size={17}/></a><a className="text-link" href="#destaques">Descobrir fragrâncias</a></div></div><p className="hero-note">Originalidade garantida · Envio para todo o Brasil</p></section>
  <section className="benefit-strip"><div className="container-site grid md:grid-cols-3">{[[ShieldCheck,"Compra segura","Ambiente protegido"],[Gem,"100% originais","Procedência garantida"],[PackageCheck,"Envio nacional","Rápido e rastreável"]].map(([Icon,title,text])=><div className="benefit" key={String(title)}><Icon size={22}/><span><b>{String(title)}</b><small>{String(text)}</small></span></div>)}</div></section>
  <section id="destaques" className="section container-site"><div className="section-heading"><div><p className="eyebrow">Curadoria S&amp;A</p><h2>Mais vendidos</h2></div><a href="/perfumes">Ver todos <ArrowRight size={16}/></a></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.slug} product={p}/>)}</div></section>
  <section className="editorial"><div className="editorial-image"/><div className="editorial-copy"><p className="eyebrow">A arte da perfumaria</p><h2>Uma assinatura<br/>só sua.</h2><p>Elegância não se anuncia. Ela permanece. Encontre notas que traduzem sua personalidade e deixam uma impressão inesquecível.</p><a className="btn-dark" href="/perfumes?genero=unissex">Explorar a coleção</a></div></section>
  <section className="section container-site"><div className="section-heading"><div><p className="eyebrow">Acabaram de chegar</p><h2>Novidades</h2></div><a href="/perfumes?ordem=recentes">Conhecer lançamentos <ArrowRight size={16}/></a></div><div className="product-grid">{products.slice(4,8).map(p=><ProductCard key={p.slug} product={p}/>)}</div></section>
  <section className="category-grid container-site"><a className="cat masculine" href="/perfumes?genero=masculino"><span>Para ele</span><h3>Masculinos</h3><b>Explorar coleção →</b></a><a className="cat feminine" href="/perfumes?genero=feminino"><span>Para ela</span><h3>Femininos</h3><b>Explorar coleção →</b></a><a className="cat arabic" href="/perfumes?categoria=arabe"><span>Intensos e opulentos</span><h3>Árabes</h3><b>Explorar coleção →</b></a></section>
  <section className="reviews section"><div className="container-site"><p className="eyebrow center">Experiências perfumadas</p><h2 className="center">Quem conhece, recomenda.</h2><div className="review-grid">{[["Marina Costa","A embalagem é impecável e o perfume chegou muito rápido. A fragrância é simplesmente maravilhosa!"],["Rafael Martins","Atendimento excelente e produto original. Já é minha segunda compra na S&A."],["Camila Alves","Consegui encontrar um perfume árabe que procurava há meses. Apaixonada pela curadoria!"]].map(([name,text])=><blockquote key={name}><div className="stars">{[1,2,3,4,5].map(x=><Star key={x} size={14} fill="currentColor"/>)}</div><p>“{text}”</p><footer>{name}<small>Compra verificada <Check size={12}/></small></footer></blockquote>)}</div></div></section>
  <section className="newsletter"><div><Sparkles size={26}/><p className="eyebrow">Círculo S&amp;A</p><h2>Receba novidades<br/>antes de todos.</h2><p>Curadorias, lançamentos e condições especiais direto no seu e-mail.</p></div><form><label className="sr-only" htmlFor="email">Seu melhor e-mail</label><input id="email" type="email" placeholder="Seu melhor e-mail" required/><button type="submit">Quero fazer parte</button></form></section>
</main><Footer/></>; }
