"use client";

import { Heart, Home, LogOut, Package, Tag, UserRound } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-client";

type Tab="orders"|"profile"|"addresses"|"favorites"|"credits";
type AccountData={profile:{name:string;email:string;cpf?:string;phone?:string};addresses:Array<Record<string,string>>;favorites:Array<{id:string;productId:string;slug:string;name:string;brand:string;image:string;price:number}>;orders:Array<{id:string;number:string;status:string;total:number;createdAt:string;items:Array<{name:string;quantity:number;price:number}>;trackingCode?:string}>;credits:number;coupons:Array<{code:string;type:string;value:number;minimumAmount?:number;validUntil?:string}>};
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const status:Record<string,string>={PENDING_PAYMENT:"Aguardando pagamento",PAID:"Pago",PREPARING:"Em preparação",SHIPPED:"Enviado",DELIVERED:"Entregue",CANCELLED:"Cancelado",REFUNDED:"Reembolsado"};

export function AccountDashboard(){
  const [tab,setTab]=useState<Tab>("orders");const [data,setData]=useState<AccountData|null>(null);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
  const request=useCallback(async(path:string,init?:RequestInit)=>{const {data:session}=await getSupabaseBrowserClient().auth.getSession();const token=session.session?.access_token;if(!token){window.location.href="/entrar";throw new Error("Sessão encerrada")};return fetch(path,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${token}`,...init?.headers}})},[]);
  const load=useCallback(async()=>{try{const response=await request("/api/account");if(!response.ok)throw new Error();setData(await response.json())}catch{setNotice("Não foi possível carregar sua conta.")}finally{setLoading(false)}},[request]);
  useEffect(()=>{load()},[load]);
  async function logout(){await getSupabaseBrowserClient().auth.signOut();window.location.href="/"}
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setNotice("");const body=Object.fromEntries(new FormData(event.currentTarget));const response=await request("/api/account",{method:"PATCH",body:JSON.stringify(body)});const result=await response.json();setNotice(response.ok?"Dados atualizados com sucesso.":result.error);if(response.ok)load()}
  async function addAddress(event:FormEvent<HTMLFormElement>){event.preventDefault();setNotice("");const response=await request("/api/account/addresses",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});const result=await response.json();setNotice(response.ok?"Endereço salvo com sucesso.":result.error);if(response.ok){event.currentTarget.reset();load()}}
  async function removeAddress(id:string){await request(`/api/account/addresses?id=${id}`,{method:"DELETE"});load()}
  async function removeFavorite(productId:string){await request(`/api/account/favorites?productId=${productId}`,{method:"DELETE"});load()}
  if(loading)return <main className="account-loading">Carregando sua conta...</main>;
  if(!data)return <main className="account-loading">{notice}</main>;
  const menu:Array<[Tab,string,typeof Package,string]>=[["orders","Pedidos",Package,"Acompanhe suas compras"],["credits","Créditos e descontos",Tag,"Confira seus benefícios"],["profile","Cadastro",UserRound,"Altere seus dados"],["addresses","Endereços",Home,"Gerencie seus endereços"],["favorites","Favoritos",Heart,"Veja seus favoritos"]];
  return <main className="account-page"><div className="account-shell"><aside className="account-sidebar"><div className="account-welcome"><UserRound/><span>Bem-vindo,<b>{data.profile.name}</b><button onClick={logout}><LogOut/> Sair da conta</button></span></div><div className="account-menu-list">{menu.map(([key,label,Icon,description])=><button key={key} className={tab===key?"active":""} onClick={()=>{setTab(key);setNotice("")}}><Icon/><span><b>{label}</b><small>{description}</small></span></button>)}</div></aside><section className="account-content">{notice&&<p className="account-notice">{notice}</p>}
    {tab==="orders"&&<><div className="account-heading"><Package/><div><p className="eyebrow">Minha conta</p><h1>Meus pedidos</h1></div></div>{data.orders.length?<div className="orders-list">{data.orders.map(order=><article key={order.id}><div><b>Pedido {order.number}</b><span>{new Date(order.createdAt).toLocaleDateString("pt-BR")}</span></div><strong>{status[order.status]||order.status}</strong><ul>{order.items.map((item,index)=><li key={index}>{item.quantity}x {item.name}</li>)}</ul><footer><b>{money(order.total)}</b>{order.trackingCode&&<span>Rastreio: {order.trackingCode}</span>}</footer></article>)}</div>:<div className="account-empty"><Package/><h2>Nenhum pedido ainda</h2><p>Suas compras aparecerão aqui.</p><a href="/perfumes">Conhecer perfumes</a></div>}</>}
    {tab==="profile"&&<><div className="account-heading"><UserRound/><div><p className="eyebrow">Seus dados</p><h1>Cadastro</h1></div></div><form className="account-form" onSubmit={saveProfile}><label>Nome completo<input name="name" defaultValue={data.profile.name} required/></label><label>E-mail<input value={data.profile.email} disabled/></label><div><label>CPF<input name="cpf" defaultValue={data.profile.cpf||""} required/></label><label>Telefone<input name="phone" defaultValue={data.profile.phone||""} required/></label></div><button>Salvar alterações</button></form></>}
    {tab==="addresses"&&<><div className="account-heading"><Home/><div><p className="eyebrow">Entrega</p><h1>Endereços</h1></div></div><div className="address-list">{data.addresses.map(a=><article key={a.id}><b>{a.street}, {a.number}</b><p>{a.district} · {a.city}/{a.state}<br/>CEP {a.zipCode}{a.complement&&<> · {a.complement}</>}</p><button onClick={()=>removeAddress(a.id)}>Remover</button></article>)}</div><form className="account-form address-form" onSubmit={addAddress}><h2>Novo endereço</h2><div><label>CEP<input name="zipCode" required/></label><label>Estado<input name="state" maxLength={2} required/></label></div><label>Rua<input name="street" required/></label><div><label>Número<input name="number" required/></label><label>Complemento<input name="complement"/></label></div><div><label>Bairro<input name="district" required/></label><label>Cidade<input name="city" required/></label></div><button>Salvar endereço</button></form></>}
    {tab==="favorites"&&<><div className="account-heading"><Heart/><div><p className="eyebrow">Sua seleção</p><h1>Favoritos</h1></div></div>{data.favorites.length?<div className="favorite-list">{data.favorites.map(item=><article key={item.id}><img src={item.image} alt={item.name}/><div><small>{item.brand}</small><a href={`/produto/${item.slug}`}><h2>{item.name}</h2></a><b>{money(item.price)}</b><button onClick={()=>removeFavorite(item.productId)}>Remover</button></div></article>)}</div>:<div className="account-empty"><Heart/><h2>Nenhum favorito</h2><p>Use o coração nos produtos para guardar suas escolhas.</p><a href="/perfumes">Explorar perfumes</a></div>}</>}
    {tab==="credits"&&<><div className="account-heading"><Tag/><div><p className="eyebrow">Benefícios</p><h1>Créditos e descontos</h1></div></div><div className="credit-balance"><span>Saldo disponível</span><b>{money(data.credits)}</b></div><h2 className="coupon-title">Cupons disponíveis</h2>{data.coupons.length?<div className="coupon-list">{data.coupons.map(c=><article key={c.code}><b>{c.code}</b><span>{c.type==="PERCENTAGE"?`${c.value}% de desconto`:`${money(c.value)} de desconto`}</span>{c.minimumAmount&&<small>Em compras acima de {money(c.minimumAmount)}</small>}</article>)}</div>:<p className="account-muted">Nenhum cupom disponível no momento.</p>}</>}
  </section></div></main>;
}
