"use client";

import { Heart, Home, LogOut, Package, Tag, UserRound } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-client";

type Tab="orders"|"profile"|"addresses"|"favorites"|"credits";
type Address={id:string;zipCode:string;street:string;number:string;complement?:string;district:string;city:string;state:string};
type AccountData={role:"CUSTOMER"|"ADMIN";profile:{name:string;email:string;cpf?:string;phone?:string};addresses:Address[];favorites:Array<{id:string;productId:string;slug:string;name:string;brand:string;image:string;price:number}>;orders:Array<{id:string;number:string;status:string;total:number;createdAt:string;items:Array<{name:string;quantity:number;price:number}>;trackingCode?:string}>;credits:number;coupons:Array<{code:string;type:string;value:number;minimumAmount?:number;validUntil?:string}>};
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const status:Record<string,string>={PENDING_PAYMENT:"Aguardando pagamento",PAID:"Pago",PREPARING:"Em preparação",SHIPPED:"Enviado",DELIVERED:"Entregue",CANCELLED:"Cancelado",REFUNDED:"Reembolsado"};

export function AccountDashboard(){
  const [tab,setTab]=useState<Tab>("orders");const [data,setData]=useState<AccountData|null>(null);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");const [changingPassword,setChangingPassword]=useState(false);const [editingAddress,setEditingAddress]=useState<Address|null>(null);const [savingAddress,setSavingAddress]=useState(false);
  const request=useCallback(async(path:string,init?:RequestInit)=>{const {data:session}=await getSupabaseBrowserClient().auth.getSession();const token=session.session?.access_token;if(!token){window.location.href="/entrar";return new Response(JSON.stringify({error:"Sessão encerrada"}),{status:401,headers:{"content-type":"application/json"}})}return fetch(path,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${token}`,...init?.headers}})},[]);
  const load=useCallback(async()=>{try{const response=await request("/api/account");if(!response.ok)throw new Error();const result:AccountData=await response.json();if(result.role==="ADMIN"){window.location.replace("/admin");return}setData(result)}catch{setNotice("Não foi possível carregar sua conta.")}finally{setLoading(false)}},[request]);
  useEffect(()=>{if(new URLSearchParams(window.location.search).get("secao")==="favoritos")setTab("favorites")},[]);
  useEffect(()=>{load()},[load]);
  async function logout(){await getSupabaseBrowserClient().auth.signOut();window.location.href="/"}
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setNotice("");const body=Object.fromEntries(new FormData(event.currentTarget));const response=await request("/api/account",{method:"PATCH",body:JSON.stringify(body)});const result=await response.json();setNotice(response.ok?"Dados atualizados com sucesso.":result.error);if(response.ok)load()}
  async function changePassword(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setNotice("");
    const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));
    const currentPassword=String(values.currentPassword||"");const newPassword=String(values.newPassword||"");const confirmPassword=String(values.confirmPassword||"");
    if(newPassword.length<8){setNotice("A nova senha deve ter pelo menos 8 caracteres.");return}
    if(newPassword!==confirmPassword){setNotice("A confirmação da nova senha não confere.");return}
    if(currentPassword===newPassword){setNotice("A nova senha deve ser diferente da senha atual.");return}
    setChangingPassword(true);
    const {error}=await getSupabaseBrowserClient().auth.updateUser({password:newPassword,current_password:currentPassword});
    setChangingPassword(false);
    if(error){setNotice(error.message.toLowerCase().includes("password")?"A senha atual está incorreta ou a nova senha não atende aos requisitos.":"Não foi possível alterar a senha.");return}
    form.reset();setNotice("Senha alterada com sucesso.");
  }
  async function saveAddress(event:FormEvent<HTMLFormElement>){event.preventDefault();setNotice("");setSavingAddress(true);const form=event.currentTarget;const body={...Object.fromEntries(new FormData(form)),id:editingAddress?.id};const response=await request("/api/account/addresses",{method:editingAddress?"PATCH":"POST",body:JSON.stringify(body)});const result=await response.json();setSavingAddress(false);if(!response.ok){setNotice(result.error);return}setData(current=>current?{...current,addresses:editingAddress?current.addresses.map(address=>address.id===result.id?result:address):[result,...current.addresses]}:current);setNotice(editingAddress?"Endereço atualizado com sucesso.":"Endereço salvo com sucesso.");setEditingAddress(null);form.reset()}
  async function removeAddress(id:string){const removed=data?.addresses.find(address=>address.id===id);setData(current=>current?{...current,addresses:current.addresses.filter(address=>address.id!==id)}:current);setNotice("Endereço removido.");const response=await request(`/api/account/addresses?id=${id}`,{method:"DELETE"});if(!response.ok&&removed){setData(current=>current?{...current,addresses:[removed,...current.addresses]}:current);setNotice("Não foi possível remover o endereço.")}}
  async function removeFavorite(productId:string){const removed=data?.favorites.find(item=>item.productId===productId);if(!removed)return;setData(current=>current?{...current,favorites:current.favorites.filter(item=>item.productId!==productId)}:current);window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{favorites:-1}}));const response=await request(`/api/account/favorites?productId=${productId}`,{method:"DELETE"});if(response.ok){window.dispatchEvent(new Event("sa:commerce-updated"));return}setData(current=>current?{...current,favorites:[removed,...current.favorites]}:current);window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{favorites:1}}));setNotice("Não foi possível remover o favorito. Tente novamente.")}
  if(loading)return <main className="account-loading">Carregando sua conta...</main>;
  if(!data)return <main className="account-loading">{notice}</main>;
  const menu:Array<[Tab,string,typeof Package,string]>=[["favorites","Favoritos",Heart,"Veja seus favoritos"],["orders","Pedidos",Package,"Acompanhe suas compras"],["addresses","Endereços",Home,"Gerencie seus endereços"],["profile","Cadastro",UserRound,"Altere seus dados"],["credits","Créditos e descontos",Tag,"Confira seus benefícios"]];
  return <main className="account-page"><div className="account-shell"><aside className="account-sidebar"><div className="account-welcome"><UserRound/><span>Bem-vindo,<b>{data.profile.name}</b><button onClick={logout}><LogOut/> Sair da conta</button></span></div><div className="account-menu-list">{menu.map(([key,label,Icon,description])=><button key={key} className={tab===key?"active":""} onClick={()=>{setTab(key);setNotice("")}}><Icon/><span><b>{label}</b><small>{description}</small></span></button>)}</div></aside><section className="account-content">{notice&&<p className="account-notice">{notice}</p>}
    {tab==="orders"&&<><div className="account-heading"><Package/><div><p className="eyebrow">Minha conta</p><h1>Meus pedidos</h1></div></div>{data.orders.length?<div className="orders-list">{data.orders.map(order=><article key={order.id}><div><b>Pedido {order.number}</b><span>{new Date(order.createdAt).toLocaleDateString("pt-BR")}</span></div><strong>{status[order.status]||order.status}</strong><ul>{order.items.map((item,index)=><li key={index}>{item.quantity}x {item.name}</li>)}</ul><footer><b>{money(order.total)}</b>{order.trackingCode&&<span>Rastreio: {order.trackingCode}</span>}</footer></article>)}</div>:<div className="account-empty"><Package/><h2>Nenhum pedido ainda</h2><p>Suas compras aparecerão aqui.</p><a href="/perfumes">Conhecer perfumes</a></div>}</>}
    {tab==="profile"&&<><div className="account-heading"><UserRound/><div><p className="eyebrow">Seus dados</p><h1>Cadastro</h1></div></div><div className="account-profile-layout"><section className="profile-card"><header><p className="eyebrow">Informações da conta</p><h2>Dados pessoais</h2></header><form className="account-form" onSubmit={saveProfile}><label>Nome completo<input name="name" defaultValue={data.profile.name} required/></label><div><label>CPF<input value={data.profile.cpf||""} disabled/></label><label>Telefone<input name="phone" defaultValue={data.profile.phone||""} required/></label></div><button>Salvar alterações</button></form></section><aside className="access-card"><header><p className="eyebrow">Segurança</p><h2>Dados de acesso</h2></header><div className="access-email"><span>E-mail cadastrado</span><strong>{data.profile.email}</strong><small>Este e-mail não pode ser alterado.</small></div><section className="password-section"><h3>Alterar senha</h3><p>Confirme sua senha atual antes de escolher uma nova.</p><form className="account-form" onSubmit={changePassword}><label>Senha atual<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>Nova senha<input name="newPassword" type="password" minLength={8} autoComplete="new-password" required/></label><label>Confirmar nova senha<input name="confirmPassword" type="password" minLength={8} autoComplete="new-password" required/></label><button disabled={changingPassword}>{changingPassword?"Alterando senha...":"Alterar senha"}</button></form></section></aside></div></>}
    {tab==="addresses"&&<><div className="account-heading"><Home/><div><p className="eyebrow">Entrega</p><h1>Endereços</h1></div></div><div className="address-list">{data.addresses.map(a=><article key={a.id}><b>{a.street}, {a.number}</b><p>{a.district} · {a.city}/{a.state}<br/>CEP {a.zipCode}{a.complement&&<> · {a.complement}</>}</p><div className="address-actions"><button onClick={()=>{setEditingAddress(a);setNotice("")}}>Editar</button><button onClick={()=>removeAddress(a.id)}>Remover</button></div></article>)}</div><form key={editingAddress?.id||"new"} className="account-form address-form" onSubmit={saveAddress}><div className="address-form-heading"><h2>{editingAddress?"Editar endereço":"Novo endereço"}</h2>{editingAddress&&<button type="button" onClick={()=>setEditingAddress(null)}>Cancelar edição</button>}</div><div><label>CEP<input name="zipCode" defaultValue={editingAddress?.zipCode} required/></label><label>Estado<input name="state" defaultValue={editingAddress?.state} maxLength={2} required/></label></div><label>Rua<input name="street" defaultValue={editingAddress?.street} required/></label><div><label>Número<input name="number" defaultValue={editingAddress?.number} required/></label><label>Complemento<input name="complement" defaultValue={editingAddress?.complement} /></label></div><div><label>Bairro<input name="district" defaultValue={editingAddress?.district} required/></label><label>Cidade<input name="city" defaultValue={editingAddress?.city} required/></label></div><button disabled={savingAddress}>{savingAddress?"Salvando...":editingAddress?"Salvar alterações":"Salvar endereço"}</button></form></>}
    {tab==="favorites"&&<><div className="account-heading"><Heart/><div><p className="eyebrow">Sua seleção</p><h1>Favoritos</h1></div></div>{data.favorites.length?<div className="favorite-list">{data.favorites.map(item=><article key={item.id}><img src={item.image} alt={item.name}/><div><small>{item.brand}</small><a href={`/produto/${item.slug}`}><h2>{item.name}</h2></a><b>{money(item.price)}</b><button onClick={()=>removeFavorite(item.productId)}>Remover</button></div></article>)}</div>:<div className="account-empty"><Heart/><h2>Nenhum favorito</h2><p>Use o coração nos produtos para guardar suas escolhas.</p><a href="/perfumes">Explorar perfumes</a></div>}</>}
    {tab==="credits"&&<><div className="account-heading"><Tag/><div><p className="eyebrow">Benefícios</p><h1>Créditos e descontos</h1></div></div><div className="credit-balance"><span>Saldo disponível</span><b>{money(data.credits)}</b></div><h2 className="coupon-title">Cupons disponíveis</h2>{data.coupons.length?<div className="coupon-list">{data.coupons.map(c=><article key={c.code}><b>{c.code}</b><span>{c.type==="PERCENTAGE"?`${c.value}% de desconto`:`${money(c.value)} de desconto`}</span>{c.minimumAmount&&<small>Em compras acima de {money(c.minimumAmount)}</small>}</article>)}</div>:<p className="account-muted">Nenhum cupom disponível no momento.</p>}</>}
  </section></div></main>;
}
