"use client";

import {Minus,Plus,ShoppingBag,Trash2} from "lucide-react";
import {useEffect,useState} from "react";
import {money} from "@/lib/catalog";
import {getSupabaseBrowserClient} from "@/lib/supabase-client";

type Item={id:string;quantity:number;unitPrice:number;product:{name:string;brand:string;volume:string;image:string;slug:string;stock:number}};
export function CartPageClient(){
  const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[pending,setPending]=useState<string[]>([]);
  async function token(){const{data}=await getSupabaseBrowserClient().auth.getSession();if(!data.session?.access_token){window.location.href=`/entrar?retorno=${encodeURIComponent("/carrinho")}`;return null}return data.session.access_token}
  async function load(){const access=await token();if(!access)return;const response=await fetch("/api/cart",{headers:{authorization:`Bearer ${access}`},cache:"no-store"});if(response.status===401){window.location.href=`/entrar?retorno=${encodeURIComponent("/carrinho")}`;return}const result=await response.json();setItems(result.items||[]);setLoading(false)}
  useEffect(()=>{void load()},[]);
  async function change(item:Item,next:number){if(next<1||next>item.product.stock||pending.includes(item.id))return;const access=await token();if(!access)return;setError("");const previous=item.quantity;setPending(current=>[...current,item.id]);setItems(current=>current.map(value=>value.id===item.id?{...value,quantity:next}:value));window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{cart:next-previous}}));const response=await fetch("/api/cart",{method:"PATCH",headers:{authorization:`Bearer ${access}`,"content-type":"application/json"},body:JSON.stringify({item:item.id,quantity:next})});if(!response.ok){const body=await response.json().catch(()=>({}));setItems(current=>current.map(value=>value.id===item.id?{...value,quantity:previous}:value));window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{cart:previous-next}}));setError(body.error||"Não foi possível alterar a quantidade.")}setPending(current=>current.filter(id=>id!==item.id));window.dispatchEvent(new Event("sa:commerce-updated"))}
  async function remove(item:Item){const access=await token();if(!access)return;setError("");const position=items.findIndex(value=>value.id===item.id);setItems(current=>current.filter(value=>value.id!==item.id));window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{cart:-item.quantity}}));const response=await fetch(`/api/cart?item=${encodeURIComponent(item.id)}`,{method:"DELETE",headers:{authorization:`Bearer ${access}`}});if(response.ok){window.dispatchEvent(new Event("sa:commerce-updated"));return}setItems(current=>{const restored=[...current];restored.splice(Math.max(0,position),0,item);return restored});window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{cart:item.quantity}}));setError("Não foi possível excluir o item. Tente novamente.")}
  const subtotal=items.reduce((sum,item)=>sum+item.unitPrice*item.quantity,0);const pix=subtotal*.95;
  if(loading)return <div className="commerce-loading">Carregando seu carrinho…</div>;
  if(!items.length)return <div className="empty-cart"><ShoppingBag/><h2>Seu carrinho está vazio.</h2><p>Encontre uma fragrância que combine com a sua história.</p><a href="/perfumes">Descobrir perfumes</a></div>;
  return <>{error&&<p className="cart-error" role="alert">{error}</p>}<div className="commerce-cart-layout"><section className="commerce-cart-items">{items.map(item=><article className="commerce-cart-item" key={item.id}><a className="commerce-cart-image" href={`/produto/${item.product.slug}`}><img src={item.product.image} alt={item.product.name}/></a><div className="commerce-cart-copy"><p>{item.product.brand}</p><h2>{item.product.name}</h2><small>{item.product.volume}</small><button className="commerce-remove" onClick={()=>remove(item)}><Trash2/> Excluir</button></div><div className="commerce-cart-quantity"><span>Quantidade</span><div><button aria-label="Diminuir quantidade" disabled={pending.includes(item.id)||item.quantity===1} onClick={()=>change(item,item.quantity-1)}><Minus/></button><b>{item.quantity}</b><button aria-label="Aumentar quantidade" disabled={pending.includes(item.id)||item.quantity>=item.product.stock} onClick={()=>change(item,item.quantity+1)}><Plus/></button></div></div><div className="commerce-cart-price"><span>Valor</span><strong>{money(item.unitPrice*item.quantity)}</strong><small>ou {money(item.unitPrice*.95*item.quantity)} no Pix</small></div></article>)}</section><aside className="commerce-summary"><h2>Resumo da compra</h2><div className="summary-line"><span>Produtos</span><b>{money(subtotal)}</b></div><div className="summary-line"><span>Entrega</span><em>Calculada na próxima etapa</em></div><div className="summary-payment highlight"><span>Pix <small>5% de desconto</small></span><strong>{money(pix)}</strong></div><div className="summary-payment"><span>Cartão <small>em até 6x sem juros</small></span><strong>{money(subtotal)}</strong></div><a className="summary-checkout" href="/checkout">Finalizar compra</a><a className="summary-back" href="/perfumes">Continuar comprando</a></aside></div></>;
}
