"use client";
import {ArrowLeft,ArrowRight,ShoppingBag,Sparkles} from "lucide-react";
import {useState} from "react";
import {money} from "@/lib/catalog";
import {getSupabaseBrowserClient} from "@/lib/supabase-client";
type Result={slug:string;name:string;brand:string;price:number;pixPrice:number;image:string;compatibility:number;characteristics:string[]};
const questions=[
  {key:"gender",title:"Para quem é o perfume?",options:["Masculino","Feminino","Unissex"]},
  {key:"styles",title:"Qual estilo de fragrância você prefere?",options:["Doce","Fresco","Cítrico","Amadeirado","Especiado","Floral"],multiple:true},
  {key:"occasion",title:"Quando pretende usar mais?",options:["Dia a dia","Trabalho","Encontros","Festas","Noite","Ocasiões especiais"]},
  {key:"intensity",title:"Qual intensidade você prefere?",options:["Discreto","Moderado","Marcante","Muito marcante"]},
  {key:"budget",title:"Quanto pretende gastar?",options:["Até R$ 200","R$ 200 a R$ 300","R$ 300 a R$ 400","Acima de R$ 400"]},
] as const;
export function PerfumeQuiz(){
  const[open,setOpen]=useState(false);const[step,setStep]=useState(0);const[answers,setAnswers]=useState<Record<string,string|string[]>>({styles:[]});const[results,setResults]=useState<Result[]|null>(null);const[loading,setLoading]=useState(false);const question=questions[step];
  function choose(option:string){if("multiple" in question&&question.multiple){const current=(answers.styles as string[])||[];setAnswers({...answers,styles:current.includes(option)?current.filter(value=>value!==option):[...current,option]})}else setAnswers({...answers,[question.key]:option})}
  function selected(option:string){const value=answers[question.key];return Array.isArray(value)?value.includes(option):value===option}
  async function finish(){setLoading(true);const budgetMin=answers.budget==="R$ 200 a R$ 300"?200:answers.budget==="R$ 300 a R$ 400"?300:answers.budget==="Acima de R$ 400"?400:null;const budgetMax=answers.budget==="Até R$ 200"?200:answers.budget==="R$ 200 a R$ 300"?300:answers.budget==="R$ 300 a R$ 400"?400:null;const response=await fetch("/api/recommendations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...answers,budgetMin,budgetMax})});setResults(response.ok?(await response.json()).products:[]);setLoading(false)}
  async function add(product:Result){const {data}=await getSupabaseBrowserClient().auth.getSession();const token=data.session?.access_token;if(!token){window.location.href=`/entrar?retorno=${encodeURIComponent("/#encontre-seu-perfume")}&acao=carrinho&produto=${product.slug}`;return}const response=await fetch("/api/cart",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({productId:product.slug,quantity:1})});if(response.ok)window.dispatchEvent(new Event("sa:commerce-updated"))}
  function restart(){setStep(0);setAnswers({styles:[]});setResults(null)}
  return <section id="encontre-seu-perfume" className="perfume-finder"><div className="container-site">{!open?<div className="finder-invite"><Sparkles/><p className="eyebrow">Encontre seu perfume</p><h2>Qual perfume combina com você?</h2><p>Responda algumas perguntas e descubra fragrâncias que combinam com seu estilo.</p><button onClick={()=>setOpen(true)}>Descobrir meu perfume <ArrowRight/></button></div>:results?<div className="finder-results"><p className="eyebrow">Curadoria personalizada</p><h2>Encontramos perfumes para você</h2>{results.length?<div className="finder-result-grid">{results.map(product=><article key={product.slug}><div className="finder-match">{product.compatibility}% compatível com você</div><img src={product.image} alt={product.name} loading="lazy"/><small>{product.brand}</small><h3>{product.name}</h3><strong>{money(product.pixPrice)} <em>no PIX</em></strong><p>No cartão: {money(product.price)}</p><div>{product.characteristics.map(value=><span key={value}>{value}</span>)}</div><footer><a href={`/produto/${product.slug}`}>Ver perfume</a><button onClick={()=>add(product)}><ShoppingBag/> Adicionar</button></footer></article>)}</div>:<p className="finder-none">Ainda não encontramos um perfume com todos esses critérios. Tente ampliar suas escolhas.</p>}<button className="finder-restart" onClick={restart}>Refazer teste</button></div>:<div className="finder-quiz"><div className="finder-progress"><span style={{width:`${((step+1)/questions.length)*100}%`}}/></div><small>Pergunta {step+1} de {questions.length}</small><h2>{question.title}</h2><div className="finder-options">{question.options.map(option=><button className={selected(option)?"selected":""} key={option} onClick={()=>choose(option)}>{option}</button>)}</div><div className="finder-nav"><button disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft/> Voltar</button>{step<questions.length-1?<button disabled={!answers[question.key]||(Array.isArray(answers[question.key])&&!(answers[question.key] as string[]).length)} onClick={()=>setStep(step+1)}>Continuar <ArrowRight/></button>:<button disabled={!answers.budget||loading} onClick={finish}>{loading?"Buscando...":"Ver meus perfumes"}</button>}</div></div>}</div></section>;
}
