"use client";

import {Heart,Minus,Plus,ShoppingBag,ShoppingCart} from "lucide-react";
import {usePathname,useSearchParams} from "next/navigation";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabase-client";

type Action="comprar"|"carrinho"|"favorito";
export function ProductActions({slug,stock}:{slug:string;stock:number}){
  const pathname=usePathname();const searchParams=useSearchParams();const[busy,setBusy]=useState<Action|null>(null);const[favorite,setFavorite]=useState<boolean|null>(null);const[notice,setNotice]=useState("");const[cartFeedback,setCartFeedback]=useState(false);const[quantity,setQuantity]=useState(1);
  useEffect(()=>{const added=searchParams.get("adicionado");if(added==="favoritos"){setFavorite(true);setNotice("Perfume adicionado aos seus favoritos.")}if(added==="removido-favoritos"){setFavorite(false);setNotice("Perfume removido dos seus favoritos.")}if(added==="carrinho")setNotice("Perfume adicionado ao seu carrinho.")},[searchParams]);
  useEffect(()=>{let active=true;(async()=>{const{data}=await getSupabaseBrowserClient().auth.getSession();const token=data.session?.access_token;if(!token){if(active)setFavorite(false);return}const response=await fetch(`/api/account/favorites?productId=${encodeURIComponent(slug)}`,{headers:{authorization:`Bearer ${token}`}});if(response.ok){const result=await response.json();if(active)setFavorite(Boolean(result.favorite))}})();return()=>{active=false}},[slug]);
  function stockMessage(){return `Este produto possui ${stock} unidade${stock===1?"":"s"} em estoque.`}
  function changeQuantity(value:number){const next=Math.max(1,Math.min(99,Math.floor(value)||1));setQuantity(next);setNotice(next>stock?stockMessage():"")}
  function loginUrl(action:Action){const query=searchParams.toString();const returnTo=`${pathname}${query?`?${query}`:""}`;return `/entrar?retorno=${encodeURIComponent(returnTo)}&acao=${action}&produto=${encodeURIComponent(slug)}&quantidade=${quantity}`}
  async function act(action:Action){
    if(busy||((action==="comprar"||action==="carrinho")&&stock<1))return;if((action==="comprar"||action==="carrinho")&&quantity>stock){setNotice(stockMessage());return}setBusy(action);setNotice("");
    const{data}=await getSupabaseBrowserClient().auth.getSession();const token=data.session?.access_token;if(!token){window.location.href=loginUrl(action);return}
    const previous=Boolean(favorite);const optimistic=!previous;if(action==="favorito"){setFavorite(optimistic);setNotice(optimistic?"Perfume adicionado aos seus favoritos.":"Perfume removido dos seus favoritos.");window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{favorites:optimistic?1:-1}}))}if(action==="carrinho"){setCartFeedback(true);setNotice("Perfume adicionado ao seu carrinho.");window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{cart:quantity}}))}
    const response=await fetch(action==="favorito"?"/api/account/favorites":"/api/cart",{method:action==="favorito"?"PATCH":"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({productId:slug,quantity})});
    if(response.status===401){if(action==="carrinho"){setCartFeedback(false);window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{cart:-quantity}}))}window.location.href=loginUrl(action);return}if(!response.ok){const result=await response.json().catch(()=>({}));if(action==="favorito"){setFavorite(previous);window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{favorites:previous?1:-1}}))}if(action==="carrinho"){setCartFeedback(false);window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{cart:-quantity}}))}setNotice(result.error||"Não foi possível concluir. Tente novamente.");setBusy(null);return}
    window.dispatchEvent(new Event("sa:commerce-updated"));if(action==="favorito"){const result=await response.json();const confirmed=Boolean(result.favorite);setFavorite(confirmed);if(confirmed!==optimistic)window.dispatchEvent(new CustomEvent("sa:commerce-optimistic",{detail:{favorites:confirmed?1:-1}}));setNotice(confirmed?"Perfume adicionado aos seus favoritos.":"Perfume removido dos seus favoritos.");setBusy(null);return}if(action==="carrinho"){setBusy(null);window.setTimeout(()=>setCartFeedback(false),1600);return}window.location.href="/checkout";
  }
  return <><div className="product-quantity"><span>Quantidade</span><div><button type="button" disabled={stock<1} onClick={()=>changeQuantity(quantity-1)} aria-label="Diminuir quantidade"><Minus/></button><input type="number" min="1" max="99" disabled={stock<1} value={quantity} onChange={event=>changeQuantity(Number(event.target.value))} aria-label="Quantidade do produto"/><button type="button" disabled={stock<1} onClick={()=>changeQuantity(quantity+1)} aria-label="Aumentar quantidade"><Plus/></button></div></div><div className="product-commerce-actions"><button className="product-buy-now" disabled={stock<1||busy!==null} onClick={()=>act("comprar")}><ShoppingBag/>{busy==="comprar"?"Preparando compra...":stock>0?"Comprar agora":"Indisponível"}</button><div><button className={`product-add-cart${cartFeedback?" added":""}`} disabled={stock<1||busy!==null} onClick={()=>act("carrinho")}><ShoppingCart/>{stock<1?"Indisponível":cartFeedback?"Adicionado ao carrinho ✓":"Adicionar ao carrinho"}</button><button className={favorite?"favorite-active":""} disabled={busy!==null} onClick={()=>act("favorito")} aria-label={favorite?"Remover dos favoritos":"Adicionar aos favoritos"}><Heart fill={favorite?"currentColor":"none"}/></button></div></div>{notice&&<p className="product-action-notice" role="status">{notice}</p>}</>;
}
