export type Product = {slug:string;name:string;brand:string;gender:string;category:string;volume:string;price:number;oldPrice?:number;image:string;badge?:string;family:string;notes:string[];styles?:string[];intensity?:string;occasions?:string[];characteristics?:string[];isArabian?:boolean;description:string;stock:number};
export const products: Product[] = [
 {slug:"liquid-brun",name:"Liquid Brun",brand:"French Avenue",gender:"Masculino",category:"Árabe",volume:"100 ml",price:389.9,oldPrice:449.9,badge:"Mais vendido",image:"https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85",family:"Oriental Amadeirado",notes:["Canela","Baunilha","Pralinê"],description:"Uma fragrância quente e envolvente, com abertura especiada e fundo cremoso de baunilha e madeiras nobres.",stock:12},
 {slug:"libre-intense",name:"Libre Intense",brand:"Yves Saint Laurent",gender:"Feminino",category:"Importado",volume:"90 ml",price:899.9,badge:"Ícone",image:"https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85",family:"Floral Oriental",notes:["Lavanda","Flor de laranjeira","Baunilha"],description:"A liberdade em sua versão mais intensa: floral, luminosa e profundamente sensual.",stock:7},
 {slug:"khamrah",name:"Khamrah",brand:"Lattafa",gender:"Unissex",category:"Árabe",volume:"100 ml",price:329.9,oldPrice:379.9,badge:"Oferta",image:"https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&w=900&q=85",family:"Oriental Especiado",notes:["Canela","Tâmara","Fava tonka"],description:"Opulento e adocicado, combina especiarias vibrantes a uma base sofisticada e duradoura.",stock:18},
 {slug:"bleu",name:"Bleu",brand:"Chanel",gender:"Masculino",category:"Importado",volume:"100 ml",price:1099.9,badge:"Clássico",image:"https://images.unsplash.com/photo-1615634262417-98ba2a474e01?auto=format&fit=crop&w=900&q=85",family:"Amadeirado Aromático",notes:["Toranja","Incenso","Sândalo"],description:"Um amadeirado aromático de presença limpa, elegante e atemporal.",stock:5},
 {slug:"good-girl",name:"Good Girl",brand:"Carolina Herrera",gender:"Feminino",category:"Importado",volume:"80 ml",price:789.9,badge:"Novidade",image:"https://images.unsplash.com/photo-1619994403073-2cec844b8e63?auto=format&fit=crop&w=900&q=85",family:"Oriental Floral",notes:["Amêndoa","Jasmim","Cacau"],description:"Contrastes luminosos e misteriosos em uma fragrância marcante e feminina.",stock:9},
 {slug:"asad",name:"Asad",brand:"Lattafa",gender:"Masculino",category:"Árabe",volume:"100 ml",price:249.9,badge:"Novidade",image:"https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=900&q=85",family:"Oriental Especiado",notes:["Pimenta preta","Café","Âmbar"],description:"Intenso, especiado e confiante, com excelente projeção e assinatura moderna.",stock:22},
 {slug:"idole",name:"Idôle",brand:"Lancôme",gender:"Feminino",category:"Importado",volume:"75 ml",price:679.9,image:"https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=85",family:"Floral Chipre",notes:["Rosa","Jasmim","Almíscar"],description:"Um floral radiante e limpo criado para mulheres que lideram seu próprio caminho.",stock:11},
 {slug:"club-de-nuit",name:"Club de Nuit",brand:"Armaf",gender:"Masculino",category:"Árabe",volume:"105 ml",price:349.9,image:"https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=900&q=85",family:"Amadeirado Frutado",notes:["Limão","Abacaxi","Bétula"],description:"Uma fragrância vibrante, elegante e reconhecida por sua presença marcante.",stock:14},
];
export const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
